spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/adopet?createDatabaseIfNotExist=true
    username: postgres
    password: root

  mail:
    host: smtp.example.com
    port: 587
    username: postgres
    password: root
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true